import Head from "next/head";
import Poker from "../components/Games/Poker/Poker.js";

export default function Home() {
  return (
    <div>
      <Head>
        <title>CRYPTGO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Poker />
    </div>
  );
}
