import Head from "next/head"
import Link from 'next/link'
export default function Home() {
  return (
    <div>
      <Head>
        <title>CRYPTGO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen w-full items-center justify-center" >
        <Link href='./poker'><button className="bg-pot4">Poker online</button></Link>
      </div>
    </div>
  );
}
